config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :agencies


  namespace :admin do
    resources :agencies
  end

  root to: "admin/agencies#index"

end

app/models/agency.rb
class Agency < ApplicationRecord

  has_many :blocks

  enum category: [:financial, :family, :food_rations, :donations, :health, :elderly, :children, :teens, :unemployment, :homeless, :mental_health, :addictions, :special_needs, :disability]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord

  belongs_to :agency
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/agencies_controller.rb
class Admin::AgenciesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_agency, only:  [:show, :edit, :update, :destroy]

  def index
    @agencies = Agency.all
  end

  def new
    @agency = Agency.new
  end

   def create
    @agency = Agency.new(agency_params)
    if @agency.save
      flash[:notice] = "Agency was successfully created"
      redirect_to admin_agencies_path
    else
      flash.now[:alert] = "Agency was failed to create"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @agency.update(agency_params)
      flash[:notice] = "rAgency was successfully updated"
      redirect_to admin_ragency_path(@agency)
    else
      flash.now[:alert] = "Agency was failed to update"
      render :edit
    end
  end

  def destroy
    @agency.destroy
    flash[:alert] = "Agency was deleted"
    redirect_to admin_agencies_path
  end

  private

  def agency_params
    params.require(:agency).permit(:name, :office_number, :fax_number, :address, :email, :website, :opening_hours, :category, :criteria, :description)
  end

  def set_agency
    @agency = Agency.find(params[:id])
  end
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/helpers/admin/agencies_helper.rb
module Admin::AgenciesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rations_helper.rb
module RationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/agencies/_form.html.erb
<% if @agency.errors.any? %>
  <div class="container ">
    <div class="row d-flex justify-content-center">
      <div class="alert alert-info col-md-6" role="alert">
        <h4>We have some errors here !</h4>
          <ul>
            <% @agency.errors.full_messages.each do |msg| %>
              <li class="mb-0"><%= msg %></li>
            <% end %>
          </ul>
        <hr>
      </div>
    </div>
  </div>
<% end %>

<div class="container ">
  <div class="row d-flex justify-content-center">
  <div class="col-md-7">
    <%= form_for [:admin, @agency] do |f| %>
    <div class="card mt-5">
      <div class="card-header">
        <h4>Forms</h4>
      <div class="card-body">
        <form>
        
          <div class="form-group">
            <%= f.label :name, "Name" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :office_number, "Office Number" %>
            <%= f.text_field :office_number, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :fax_number, "Fax Number" %>
            <%= f.text_field :fax_number, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :adddress, "Address" %>
            <%= f.text_field :address, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :email, "E-mail" %>
            <%= f.text_field :email, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :website, "Website" %>
            <%= f.text_field :website, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :opening_hours, "Opening Hours" %>
            <%= f.text_field :opening_hours, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :category, "Category" %>
            <%= f.select :category, Agency.categories.keys.to_a, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :criteria, "Criteria" %>
            <%= f.text_field :criteria, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :description, "Description" %>
            <%= f.text_field :description, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.submit class: "btn btn-primary" %>
          </div>
        </form>
      </div>
      </div>
    </div>
     <% end %>
  </div>

  </div>
</div

app/views/admin/agencies/edit.html.erb
<%= render partial: "form" %>

app/views/admin/agencies/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Agencies</h1>
      <br>
      <div>
        <%= link_to 'New Agency', new_admin_agency_path, class: "btn btn-primary" %>
      </div>
      <br>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Category</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @agencies.each do |agency| %>
          <tr>
            <td><%= agency.name %></td>
            <td><%= agency.category %></td>
            <td>
              <%= link_to 'Show', admin_agency_path(agency) %>
              <%= link_to 'Edit', edit_admin_agency_path(agency) %>
              <%= link_to 'Delete', admin_agency_path(agency), method: :delete, data: {confirm:"Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/agencies/new.html.erb
<%= render partial: "form" %>

app/views/admin/agencies/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @agency.name %>
</p>

<p>
  <strong>Office Number:</strong>
  <%= @agency.office_number %>
</p>

<p>
  <strong>Fax Number:</strong>
  <td><%= @agency.fax_number %></td>
</p>
<p>
  <strong>Address:</strong>
  <td><%= @agency.address %></td>
</p>
<p>
  <strong>Email:</strong>
  <td><%= @agency.email %></td>
</p>
<p>
  <strong>Website:</strong>
  <td><%= @agency.website %></td>
</p>
<p>
  <strong>Opening Hours:</strong>
  <td><%= @agency.opening_hours %></td>
</p>
<p>
  <strong>Category:</strong>
  <td><%= @agency.category %></td>
</p>
<p>
  <strong>Criteria:</strong>
  <td><%= @agency.criteria %></td>
</p>
<p>
  <strong>Description:</strong>
  <td><%= @agency.description%></td>
</p>

<%= link_to 'Edit', edit_admin_agency_path(@agency), class: 'btn btn-primary'%>
<%= link_to 'Back Index', admin_agencies_path, class: 'btn btn-info'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Searchapp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Home", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
          <% if current_user %>
            <li class="nav-item navbar-nav "><%= link_to('Log out', destroy_user_session_path, method: :delete, class: 'nav-link') %></li> 
            <li class="nav-item navbar-nav "><%= link_to('Change password', edit_user_registration_path , class: 'nav-link') %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  </body>
</html>